create table Users (
    id number generated by default as identity,
    name varchar2(255) not null
);

insert into Users (id, name) values (1, 'John');
insert into Users (id, name) values (2, 'Jane');
